const curriculum = [
  // =====================================
  // 🌱 레벨 1: 기본 부수 (23개)
  // =====================================
  {
    day: 1,
    level: 1,
    emoji: '👤',
    radical: {
      char: '人',
      name: '사람 인',
      cnName: '人字旁',
      pinyin: 'rén',
      desc: '사람',
    },
    related: [
      { char: '人', name: '사람 인', pinyin: 'rén' },
      { char: '从', name: '좇을 종', pinyin: 'cóng' },
      { char: '众', name: '무리 중', pinyin: 'zhòng' },
      { char: '今', name: '이제 금', pinyin: 'jīn' },
      { char: '会', name: '모일 회', pinyin: 'huì' },
    ],
  },
  {
    day: 2,
    level: 1,
    emoji: '👄',
    radical: {
      char: '口',
      name: '입 구',
      cnName: '口字旁',
      pinyin: 'kǒu',
      desc: '입',
    },
    related: [
      { char: '口', name: '입 구', pinyin: 'kǒu' },
      { char: '吃', name: '먹을 끽', pinyin: 'chī' },
      { char: '喝', name: '마실 갈', pinyin: 'hē' },
      { char: '叫', name: '부를 규', pinyin: 'jiào' },
      { char: '唱', name: '부를 창', pinyin: 'chàng' },
    ],
  },
  {
    day: 3,
    level: 1,
    emoji: '🌳',
    radical: {
      char: '木',
      name: '나무 목',
      cnName: '木字旁',
      pinyin: 'mù',
      desc: '나무',
    },
    related: [
      { char: '木', name: '나무 목', pinyin: 'mù' },
      { char: '林', name: '수풀 림', pinyin: 'lín' },
      { char: '森', name: '빽빽할 삼', pinyin: 'sēn' },
      { char: '校', name: '학교 교', pinyin: 'xiào' },
      { char: '树', name: '나무 수', pinyin: 'shù' },
    ],
  },
  {
    day: 4,
    level: 1,
    emoji: '💧',
    radical: {
      char: '水',
      name: '물 수',
      cnName: '水字旁',
      pinyin: 'shuǐ',
      desc: '물',
    },
    related: [
      { char: '水', name: '물 수', pinyin: 'shuǐ' },
      { char: '永', name: '길 영', pinyin: 'yǒng' },
      { char: '泉', name: '샘 천', pinyin: 'quán' },
      { char: '求', name: '구할 구', pinyin: 'qiú' },
      { char: '泰', name: '클 태', pinyin: 'tài' },
    ],
  },
  {
    day: 5,
    level: 1,
    emoji: '🔥',
    radical: {
      char: '火',
      name: '불 화',
      cnName: '火字旁',
      pinyin: 'huǒ',
      desc: '불',
    },
    related: [
      { char: '火', name: '불 화', pinyin: 'huǒ' },
      { char: '灯', name: '등 등', pinyin: 'dēng' },
      { char: '烧', name: '사를 소', pinyin: 'shāo' },
      { char: '炒', name: '볶을 초', pinyin: 'chǎo' },
      { char: '炎', name: '불꽃 염', pinyin: 'yán' },
    ],
  },
  {
    day: 6,
    level: 1,
    emoji: '☀️',
    radical: {
      char: '日',
      name: '날 일',
      cnName: '日字旁',
      pinyin: 'rì',
      desc: '해',
    },
    related: [
      { char: '日', name: '날 일', pinyin: 'rì' },
      { char: '明', name: '밝을 명', pinyin: 'míng' },
      { char: '早', name: '이를 조', pinyin: 'zǎo' },
      { char: '时', name: '때 시', pinyin: 'shí' },
      { char: '晚', name: '늦을 만', pinyin: 'wǎn' },
    ],
  },
  {
    day: 7,
    level: 1,
    emoji: '🌙',
    radical: {
      char: '月',
      name: '달 월',
      cnName: '月字旁',
      pinyin: 'yuè',
      desc: '달',
    },
    related: [
      { char: '月', name: '달 월', pinyin: 'yuè' },
      { char: '明', name: '밝을 명', pinyin: 'míng' },
      { char: '朋', name: '벗 붕', pinyin: 'péng' },
      { char: '期', name: '기약할 기', pinyin: 'qī' },
      { char: '朗', name: '밝을 랑', pinyin: 'lǎng' },
    ],
  },
  {
    day: 8,
    level: 1,
    emoji: '⛰️',
    radical: {
      char: '山',
      name: '메 산',
      cnName: '山字旁',
      pinyin: 'shān',
      desc: '산',
    },
    related: [
      { char: '山', name: '메 산', pinyin: 'shān' },
      { char: '岛', name: '섬 도', pinyin: 'dǎo' },
      { char: '岩', name: '바위 암', pinyin: 'yán' },
      { char: '岸', name: '언덕 안', pinyin: 'àn' },
      { char: '峰', name: '봉우리 봉', pinyin: 'fēng' },
    ],
  },
  {
    day: 9,
    level: 1,
    emoji: '👩',
    radical: {
      char: '女',
      name: '계집 녀',
      cnName: '女字旁',
      pinyin: 'nǚ',
      desc: '여자',
    },
    related: [
      { char: '女', name: '계집 녀', pinyin: 'nǚ' },
      { char: '好', name: '좋을 호', pinyin: 'hǎo' },
      { char: '妈', name: '엄마 마', pinyin: 'mā' },
      { char: '姐', name: '누이 저', pinyin: 'jiě' },
      { char: '妹', name: '누이 매', pinyin: 'mèi' },
    ],
  },
  {
    day: 10,
    level: 1,
    emoji: '👶',
    radical: {
      char: '子',
      name: '아들 자',
      cnName: '子字旁',
      pinyin: 'zǐ',
      desc: '아이',
    },
    related: [
      { char: '子', name: '아들 자', pinyin: 'zǐ' },
      { char: '字', name: '글자 자', pinyin: 'zì' },
      { char: '学', name: '배울 학', pinyin: 'xué' },
      { char: '孩', name: '아이 해', pinyin: 'hái' },
      { char: '孙', name: '손자 손', pinyin: 'sūn' },
    ],
  },
  {
    day: 11,
    level: 1,
    emoji: '👀',
    radical: {
      char: '目',
      name: '눈 목',
      cnName: '目字旁',
      pinyin: 'mù',
      desc: '눈',
    },
    related: [
      { char: '目', name: '눈 목', pinyin: 'mù' },
      { char: '看', name: '볼 간', pinyin: 'kàn' },
      { char: '眼', name: '눈 안', pinyin: 'yǎn' },
      { char: '睛', name: '눈동자 정', pinyin: 'jīng' },
      { char: '睡', name: '잘 수', pinyin: 'shuì' },
    ],
  },
  {
    day: 12,
    level: 1,
    emoji: '👂',
    radical: {
      char: '耳',
      name: '귀 이',
      cnName: '耳字旁',
      pinyin: 'ěr',
      desc: '귀',
    },
    related: [
      { char: '耳', name: '귀 이', pinyin: 'ěr' },
      { char: '闻', name: '들을 문', pinyin: 'wén' },
      { char: '聪', name: '밝을 총', pinyin: 'cōng' },
      { char: '联', name: '이을 련', pinyin: 'lián' },
      { char: '取', name: '취할 취', pinyin: 'qǔ' },
    ],
  },
  {
    day: 13,
    level: 1,
    emoji: '✋',
    radical: {
      char: '手',
      name: '손 수',
      cnName: '手字旁',
      pinyin: 'shǒu',
      desc: '손',
    },
    related: [
      { char: '手', name: '손 수', pinyin: 'shǒu' },
      { char: '拿', name: '잡을 나', pinyin: 'ná' },
      { char: '拜', name: '절 배', pinyin: 'bài' },
      { char: '拳', name: '주먹 권', pinyin: 'quán' },
      { char: '掌', name: '손바닥 장', pinyin: 'zhǎng' },
    ],
  },
  {
    day: 14,
    level: 1,
    emoji: '👣',
    radical: {
      char: '足',
      name: '발 족',
      cnName: '足字旁',
      pinyin: 'zú',
      desc: '발',
    },
    related: [
      { char: '足', name: '발 족', pinyin: 'zú' },
      { char: '跑', name: '달릴 포', pinyin: 'pǎo' },
      { char: '跳', name: '뛸 도', pinyin: 'tiào' },
      { char: '踢', name: '찰 척', pinyin: 'tī' },
      { char: '跟', name: '발뒤꿈치 근', pinyin: 'gēn' },
    ],
  },
  {
    day: 15,
    level: 1,
    emoji: '❤️',
    radical: {
      char: '心',
      name: '마음 심',
      cnName: '心字底',
      pinyin: 'xīn',
      desc: '마음',
    },
    related: [
      { char: '心', name: '마음 심', pinyin: 'xīn' },
      { char: '想', name: '생각할 상', pinyin: 'xiǎng' },
      { char: '念', name: '생각 념', pinyin: 'niàn' },
      { char: '忘', name: '잊을 망', pinyin: 'wàng' },
      { char: '感', name: '느낄 감', pinyin: 'gǎn' },
    ],
  },
  {
    day: 16,
    level: 1,
    emoji: '🌧️',
    radical: {
      char: '雨',
      name: '비 우',
      cnName: '雨字头',
      pinyin: 'yǔ',
      desc: '비',
    },
    related: [
      { char: '雨', name: '비 우', pinyin: 'yǔ' },
      { char: '雪', name: '눈 설', pinyin: 'xuě' },
      { char: '雷', name: '우레 뢰', pinyin: 'léi' },
      { char: '雾', name: '안개 무', pinyin: 'wù' },
      { char: '露', name: '이슬 로', pinyin: 'lù' },
    ],
  },
  {
    day: 17,
    level: 1,
    emoji: '🚪',
    radical: {
      char: '门',
      name: '문 문',
      cnName: '门字框',
      pinyin: 'mén',
      desc: '문',
    },
    related: [
      { char: '门', name: '문 문', pinyin: 'mén' },
      { char: '问', name: '물을 문', pinyin: 'wèn' },
      { char: '间', name: '사이 간', pinyin: 'jiān' },
      { char: '闭', name: '닫을 폐', pinyin: 'bì' },
      { char: '闹', name: '시끄러울 뇨', pinyin: 'nào' },
    ],
  },
  {
    day: 18,
    level: 1,
    emoji: '🏠',
    radical: {
      char: '宀',
      name: '갓머리',
      cnName: '宝盖头',
      pinyin: 'mián',
      desc: '집',
    },
    related: [
      { char: '家', name: '집 가', pinyin: 'jiā' },
      { char: '字', name: '글자 자', pinyin: 'zì' },
      { char: '安', name: '편안 안', pinyin: 'ān' },
      { char: '完', name: '완전할 완', pinyin: 'wán' },
      { char: '宝', name: '보배 보', pinyin: 'bǎo' },
    ],
  },
  {
    day: 19,
    level: 1,
    emoji: '🌿',
    radical: {
      char: '艹',
      name: '초두머리',
      cnName: '草字头',
      pinyin: 'cǎo',
      desc: '풀',
    },
    related: [
      { char: '花', name: '꽃 화', pinyin: 'huā' },
      { char: '草', name: '풀 초', pinyin: 'cǎo' },
      { char: '茶', name: '차 다', pinyin: 'chá' },
      { char: '菜', name: '나물 채', pinyin: 'cài' },
      { char: '药', name: '약 약', pinyin: 'yào' },
    ],
  },
  {
    day: 20,
    level: 1,
    emoji: '🗣️',
    radical: {
      char: '言',
      name: '말씀 언',
      cnName: '言字旁',
      pinyin: 'yán',
      desc: '말',
    },
    related: [
      { char: '言', name: '말씀 언', pinyin: 'yán' },
      { char: '誓', name: '맹세할 서', pinyin: 'shì' },
      { char: '警', name: '경계할 경', pinyin: 'jǐng' },
      { char: '誉', name: '기릴 예', pinyin: 'yù' },
      { char: '詹', name: '이를 첨', pinyin: 'zhān' },
    ],
  },
  {
    day: 21,
    level: 1,
    emoji: '⚙️',
    radical: {
      char: '金',
      name: '쇠 금',
      cnName: '金字旁',
      pinyin: 'jīn',
      desc: '쇠',
    },
    related: [
      { char: '金', name: '쇠 금', pinyin: 'jīn' },
      { char: '鑫', name: '기쁠 흠', pinyin: 'xīn' },
      { char: '鉴', name: '거울 감', pinyin: 'jiàn' },
      { char: '銮', name: '방울 란', pinyin: 'luán' },
      { char: '鎏', name: '맑을 류', pinyin: 'liú' },
    ],
  },
  {
    day: 22,
    level: 1,
    emoji: '🍚',
    radical: {
      char: '食',
      name: '밥 식',
      cnName: '食字旁',
      pinyin: 'shí',
      desc: '먹다',
    },
    related: [
      { char: '食', name: '밥 식', pinyin: 'shí' },
      { char: '餐', name: '밥 찬', pinyin: 'cān' },
      { char: '养', name: '기를 양', pinyin: 'yǎng' },
      { char: '饕', name: '탐할 도', pinyin: 'tāo' },
      { char: '餮', name: '탐할 철', pinyin: 'tiè' },
    ],
  },
  {
    day: 23,
    level: 1,
    emoji: '🧵',
    radical: {
      char: '糸',
      name: '실 사',
      cnName: '绞丝底',
      pinyin: 'mì',
      desc: '실',
    },
    related: [
      { char: '糸', name: '실 사', pinyin: 'mì' },
      { char: '系', name: '맬 계', pinyin: 'xì' },
      { char: '素', name: '흴 소', pinyin: 'sù' },
      { char: '索', name: '찾을 색', pinyin: 'suǒ' },
      { char: '紧', name: '얽을 긴', pinyin: 'jǐn' },
    ],
  },

  // =====================================
  // 🔄 레벨 2: 변신 부수 (17개)
  // =====================================
  {
    day: 24,
    level: 2,
    emoji: '👤',
    radical: {
      char: '亻',
      name: '사람인변',
      cnName: '单人旁',
      pinyin: 'rén',
      desc: '사람(人)',
    },
    related: [
      { char: '你', name: '너 니', pinyin: 'nǐ' },
      { char: '他', name: '다를 타', pinyin: 'tā' },
      { char: '们', name: '들 문', pinyin: 'men' },
      { char: '住', name: '살 주', pinyin: 'zhù' },
      { char: '做', name: '지을 주', pinyin: 'zuò' },
    ],
  },
  {
    day: 25,
    level: 2,
    emoji: '💧',
    radical: {
      char: '氵',
      name: '삼수변',
      cnName: '三点水',
      pinyin: 'shuǐ',
      desc: '물(水)',
    },
    related: [
      { char: '河', name: '강 하', pinyin: 'hé' },
      { char: '海', name: '바다 해', pinyin: 'hǎi' },
      { char: '湖', name: '호수 호', pinyin: 'hú' },
      { char: '洗', name: '씻을 세', pinyin: 'xǐ' },
      { char: '酒', name: '술 주', pinyin: 'jiǔ' },
    ],
  },
  {
    day: 26,
    level: 2,
    emoji: '✋',
    radical: {
      char: '扌',
      name: '재방변',
      cnName: '提手旁',
      pinyin: 'shǒu',
      desc: '손(手)',
    },
    related: [
      { char: '打', name: '칠 타', pinyin: 'dǎ' },
      { char: '找', name: '찾을 조', pinyin: 'zhǎo' },
      { char: '拉', name: '끌 랍', pinyin: 'lā' },
      { char: '推', name: '밀 추', pinyin: 'tuī' },
      { char: '接', name: '이을 접', pinyin: 'jiē' },
    ],
  },
  {
    day: 27,
    level: 2,
    emoji: '❤️',
    radical: {
      char: '忄',
      name: '심방변',
      cnName: '竖心旁',
      pinyin: 'xīn',
      desc: '마음(心)',
    },
    related: [
      { char: '情', name: '뜻 정', pinyin: 'qíng' },
      { char: '快', name: '쾌할 쾌', pinyin: 'kuài' },
      { char: '怕', name: '두려워할 파', pinyin: 'pà' },
      { char: '忙', name: '바플 망', pinyin: 'máng' },
      { char: '性', name: '성품 성', pinyin: 'xìng' },
    ],
  },
  {
    day: 28,
    level: 2,
    emoji: '🗣️',
    radical: {
      char: '讠',
      name: '말씀언변',
      cnName: '言字旁',
      pinyin: 'yán',
      desc: '말(言)',
    },
    related: [
      { char: '说', name: '말씀 설', pinyin: 'shuō' },
      { char: '话', name: '말씀 화', pinyin: 'huà' },
      { char: '请', name: '청할 청', pinyin: 'qǐng' },
      { char: '语', name: '말씀 어', pinyin: 'yǔ' },
      { char: '讲', name: '외울 강', pinyin: 'jiǎng' },
    ],
  },
  {
    day: 29,
    level: 2,
    emoji: '🍚',
    radical: {
      char: '饣',
      name: '식변',
      cnName: '食字旁',
      pinyin: 'shí',
      desc: '음식(食)',
    },
    related: [
      { char: '饭', name: '밥 반', pinyin: 'fàn' },
      { char: '饱', name: '배부를 포', pinyin: 'bǎo' },
      { char: '饮', name: '마실 음', pinyin: 'yǐn' },
      { char: '馆', name: '집 관', pinyin: 'guǎn' },
      { char: '饿', name: '주릴 아', pinyin: 'è' },
    ],
  },
  {
    day: 30,
    level: 2,
    emoji: '⚙️',
    radical: {
      char: '钅',
      name: '쇠금변',
      cnName: '金字旁',
      pinyin: 'jīn',
      desc: '쇠(金)',
    },
    related: [
      { char: '钱', name: '돈 전', pinyin: 'qián' },
      { char: '银', name: '은 은', pinyin: 'yín' },
      { char: '铁', name: '쇠 철', pinyin: 'tiě' },
      { char: '铜', name: '구리 동', pinyin: 'tóng' },
      { char: '钟', name: '쇠북 종', pinyin: 'zhōng' },
    ],
  },
  {
    day: 31,
    level: 2,
    emoji: '🧵',
    radical: {
      char: '纟',
      name: '실사변',
      cnName: '绞丝旁',
      pinyin: 'mì',
      desc: '실(糸)',
    },
    related: [
      { char: '红', name: '붉을 홍', pinyin: 'hóng' },
      { char: '绿', name: '푸를 록', pinyin: 'lǜ' },
      { char: '给', name: '줄 급', pinyin: 'gěi' },
      { char: '级', name: '등급 급', pinyin: 'jí' },
      { char: '纸', name: '종이 지', pinyin: 'zhǐ' },
    ],
  },
  {
    day: 32,
    level: 2,
    emoji: '🐶',
    radical: {
      char: '犭',
      name: '개사슴록변',
      cnName: '反犬旁',
      pinyin: 'quǎn',
      desc: '동물(犬)',
    },
    related: [
      { char: '狗', name: '개 구', pinyin: 'gǒu' },
      { char: '猫', name: '고양이 묘', pinyin: 'māo' },
      { char: '狼', name: '이리 랑', pinyin: 'láng' },
      { char: '猴', name: '원숭이 후', pinyin: 'hóu' },
      { char: '猪', name: '돼지 저', pinyin: 'zhū' },
    ],
  },
  {
    day: 33,
    level: 2,
    emoji: '🙏',
    radical: {
      char: '礻',
      name: '보일시변',
      cnName: '示字旁',
      pinyin: 'shì',
      desc: '제사·복(示)',
    },
    related: [
      { char: '神', name: '귀신 신', pinyin: 'shén' },
      { char: '祖', name: '할아비 조', pinyin: 'zǔ' },
      { char: '祝', name: '빌 축', pinyin: 'zhù' },
      { char: '福', name: '복 복', pinyin: 'fú' },
      { char: '礼', name: '예도 례', pinyin: 'lǐ' },
    ],
  },
  {
    day: 34,
    level: 2,
    emoji: '🔪',
    radical: {
      char: '刂',
      name: '선칼도방',
      cnName: '立刀旁',
      pinyin: 'dāo',
      desc: '칼(刀)',
    },
    related: [
      { char: '到', name: '이를 도', pinyin: 'dào' },
      { char: '别', name: '다를 별', pinyin: 'bié' },
      { char: '利', name: '이로울 리', pinyin: 'lì' },
      { char: '刻', name: '새길 각', pinyin: 'kè' },
      { char: '列', name: '벌일 렬', pinyin: 'liè' },
    ],
  },
  {
    day: 35,
    level: 2,
    emoji: '🚶',
    radical: {
      char: '辶',
      name: '책받침',
      cnName: '走之旁',
      pinyin: 'chuò',
      desc: '가다(辵)',
    },
    related: [
      { char: '这', name: '이 저', pinyin: 'zhè' },
      { char: '过', name: '지날 과', pinyin: 'guò' },
      { char: '近', name: '가까울 근', pinyin: 'jìn' },
      { char: '远', name: '멀 원', pinyin: 'yuǎn' },
      { char: '进', name: '나아갈 진', pinyin: 'jìn' },
    ],
  },
  {
    day: 36,
    level: 2,
    emoji: '🏘️',
    radical: {
      char: '阝',
      name: '좌/우부방',
      cnName: '双耳旁',
      pinyin: 'fù',
      desc: '언덕·마을(阜/邑)',
    },
    related: [
      { char: '队', name: '무리 대', pinyin: 'duì' },
      { char: '阳', name: '볕 양', pinyin: 'yáng' },
      { char: '院', name: '집 원', pinyin: 'yuàn' },
      { char: '都', name: '도읍 도', pinyin: 'dōu' },
      { char: '那', name: '어찌 나', pinyin: 'nà' },
    ],
  },
  {
    day: 37,
    level: 2,
    emoji: '👕',
    radical: {
      char: '衤',
      name: '옷의변',
      cnName: '衣字旁',
      pinyin: 'yī',
      desc: '옷(衣)',
    },
    related: [
      { char: '裤', name: '바지 고', pinyin: 'kù' },
      { char: '衬', name: '속옷 친', pinyin: 'chèn' },
      { char: '被', name: '이불 피', pinyin: 'bèi' },
      { char: '袜', name: '버선 말', pinyin: 'wà' },
      { char: '裙', name: '치마 군', pinyin: 'qún' },
    ],
  },
  {
    day: 38,
    level: 2,
    emoji: '🔥',
    radical: {
      char: '灬',
      name: '연화발',
      cnName: '四点底',
      pinyin: 'huǒ',
      desc: '불(火)',
    },
    related: [
      { char: '热', name: '더울 열', pinyin: 'rè' },
      { char: '煮', name: '삶을 자', pinyin: 'zhǔ' },
      { char: '然', name: '그러할 연', pinyin: 'rán' },
      { char: '熟', name: '익을 숙', pinyin: 'shú' },
      { char: '黑', name: '검을 흑', pinyin: 'hēi' },
    ],
  },
  {
    day: 39,
    level: 2,
    emoji: '🧊',
    radical: {
      char: '冫',
      name: '이수변',
      cnName: '两点水',
      pinyin: 'bīng',
      desc: '얼음(冰)',
    },
    related: [
      { char: '冷', name: '찰 랭', pinyin: 'lěng' },
      { char: '冰', name: '얼음 빙', pinyin: 'bīng' },
      { char: '冻', name: '얼 동', pinyin: 'dòng' },
      { char: '净', name: '깨끗할 정', pinyin: 'jìng' },
      { char: '凉', name: '서늘할 량', pinyin: 'liáng' },
    ],
  },
  {
    day: 40,
    level: 2,
    emoji: '🌙',
    radical: {
      char: '⺼',
      name: '육달월',
      cnName: '肉月旁',
      pinyin: 'ròu',
      desc: '고기·몸(肉)',
    },
    related: [
      { char: '胖', name: '살찔 반', pinyin: 'pàng' },
      { char: '肚', name: '배 두', pinyin: 'dù' },
      { char: '脚', name: '다리 각', pinyin: 'jiǎo' },
      { char: '脸', name: '뺨 렴', pinyin: 'liǎn' },
      { char: '腿', name: '넓적다리 퇴', pinyin: 'tuǐ' },
    ],
  },

  // =====================================
  // 🌿 레벨 3: 자연·사물 부수 (20개)
  // =====================================
  {
    day: 41,
    level: 3,
    emoji: '🌾',
    radical: {
      char: '田',
      name: '밭 전',
      cnName: '田字旁',
      pinyin: 'tián',
      desc: '밭',
    },
    related: [
      { char: '田', name: '밭 전', pinyin: 'tián' },
      { char: '男', name: '사내 남', pinyin: 'nán' },
      { char: '界', name: '지경 계', pinyin: 'jiè' },
      { char: '留', name: '머무를 류', pinyin: 'liú' },
      { char: '畔', name: '두둑 반', pinyin: 'pàn' },
    ],
  },
  {
    day: 42,
    level: 3,
    emoji: '🪨',
    radical: {
      char: '石',
      name: '돌 석',
      cnName: '石字旁',
      pinyin: 'shí',
      desc: '돌',
    },
    related: [
      { char: '石', name: '돌 석', pinyin: 'shí' },
      { char: '矿', name: '쇳돌 광', pinyin: 'kuàng' },
      { char: '码', name: '마노 마', pinyin: 'mǎ' },
      { char: '破', name: '깨뜨릴 파', pinyin: 'pò' },
      { char: '硬', name: '굳을 경', pinyin: 'yìng' },
    ],
  },
  {
    day: 43,
    level: 3,
    emoji: '🎋',
    radical: {
      char: '竹',
      name: '대 죽',
      cnName: '竹字头',
      pinyin: 'zhú',
      desc: '대나무',
    },
    related: [
      { char: '竹', name: '대 죽', pinyin: 'zhú' },
      { char: '笑', name: '웃을 소', pinyin: 'xiào' },
      { char: '笔', name: '붓 필', pinyin: 'bǐ' },
      { char: '第', name: '차례 제', pinyin: 'dì' },
      { char: '等', name: '무리 등', pinyin: 'děng' },
    ],
  },
  {
    day: 44,
    level: 3,
    emoji: '🐚',
    radical: {
      char: '贝',
      name: '조개 패',
      cnName: '贝字旁',
      pinyin: 'bèi',
      desc: '조개·돈',
    },
    related: [
      { char: '贝', name: '조개 패', pinyin: 'bèi' },
      { char: '财', name: '재물 재', pinyin: 'cái' },
      { char: '货', name: '재물 화', pinyin: 'huò' },
      { char: '贵', name: '귀할 귀', pinyin: 'guì' },
      { char: '贺', name: '하례할 하', pinyin: 'hè' },
    ],
  },
  {
    day: 45,
    level: 3,
    emoji: '🐴',
    radical: {
      char: '马',
      name: '말 마',
      cnName: '马字旁',
      pinyin: 'mǎ',
      desc: '말',
    },
    related: [
      { char: '马', name: '말 마', pinyin: 'mǎ' },
      { char: '妈', name: '엄마 마', pinyin: 'mā' },
      { char: '吗', name: '의문 마', pinyin: 'ma' },
      { char: '骑', name: '말탈 기', pinyin: 'qí' },
      { char: '骂', name: '꾸짖을 매', pinyin: 'mà' },
    ],
  },
  {
    day: 46,
    level: 3,
    emoji: '🐦',
    radical: {
      char: '鸟',
      name: '새 조',
      cnName: '鸟字旁',
      pinyin: 'niǎo',
      desc: '새',
    },
    related: [
      { char: '鸟', name: '새 조', pinyin: 'niǎo' },
      { char: '鸡', name: '닭 계', pinyin: 'jī' },
      { char: '鸭', name: '오리 압', pinyin: 'yā' },
      { char: '鹅', name: '거위 아', pinyin: 'é' },
      { char: '鸽', name: '비둘기 합', pinyin: 'gē' },
    ],
  },
  {
    day: 47,
    level: 3,
    emoji: '🐟',
    radical: {
      char: '鱼',
      name: '물고기 어',
      cnName: '鱼字旁',
      pinyin: 'yú',
      desc: '물고기',
    },
    related: [
      { char: '鱼', name: '물고기 어', pinyin: 'yú' },
      { char: '鲜', name: '고기 선', pinyin: 'xiān' },
      { char: '鲸', name: '고래 경', pinyin: 'jīng' },
      { char: '鲤', name: '잉어 리', pinyin: 'lǐ' },
      { char: '鲍', name: '절인고기 포', pinyin: 'bào' },
    ],
  },
  {
    day: 48,
    level: 3,
    emoji: '🐮',
    radical: {
      char: '牛',
      name: '소 우',
      cnName: '牛字旁',
      pinyin: 'niú',
      desc: '소',
    },
    related: [
      { char: '牛', name: '소 우', pinyin: 'niú' },
      { char: '物', name: '만물 물', pinyin: 'wù' },
      { char: '特', name: '특별할 특', pinyin: 'tè' },
      { char: '牧', name: '칠 목', pinyin: 'mù' },
      { char: '牵', name: '끌 견', pinyin: 'qiān' },
    ],
  },
  {
    day: 49,
    level: 3,
    emoji: '🐑',
    radical: {
      char: '羊',
      name: '양 양',
      cnName: '羊字旁',
      pinyin: 'yáng',
      desc: '양',
    },
    related: [
      { char: '羊', name: '양 양', pinyin: 'yáng' },
      { char: '美', name: '아름다울 미', pinyin: 'měi' },
      { char: '群', name: '무리 군', pinyin: 'qún' },
      { char: '鲜', name: '고운 선', pinyin: 'xiān' },
      { char: '羚', name: '영양 령', pinyin: 'líng' },
    ],
  },
  {
    day: 50,
    level: 3,
    emoji: '💎',
    radical: {
      char: '王',
      name: '구슬옥변',
      cnName: '王字旁',
      pinyin: 'wáng',
      desc: '옥',
    },
    related: [
      { char: '王', name: '임금 왕', pinyin: 'wáng' },
      { char: '玩', name: '희롱할 완', pinyin: 'wán' },
      { char: '班', name: '나눌 반', pinyin: 'bān' },
      { char: '现', name: '나타날 현', pinyin: 'xiàn' },
      { char: '理', name: '다스릴 리', pinyin: 'lǐ' },
    ],
  },
  {
    day: 51,
    level: 3,
    emoji: '🚗',
    radical: {
      char: '车',
      name: '수레 거',
      cnName: '车字旁',
      pinyin: 'chē',
      desc: '수레',
    },
    related: [
      { char: '车', name: '수레 거', pinyin: 'chē' },
      { char: '轮', name: '바퀴 륜', pinyin: 'lún' },
      { char: '转', name: '구를 전', pinyin: 'zhuǎn' },
      { char: '轻', name: '가벼울 경', pinyin: 'qīng' },
      { char: '辆', name: '수레 량', pinyin: 'liàng' },
    ],
  },
  {
    day: 52,
    level: 3,
    emoji: '🚢',
    radical: {
      char: '舟',
      name: '배 주',
      cnName: '舟字旁',
      pinyin: 'zhōu',
      desc: '배',
    },
    related: [
      { char: '舟', name: '배 주', pinyin: 'zhōu' },
      { char: '船', name: '배 선', pinyin: 'chuán' },
      { char: '航', name: '배 항', pinyin: 'háng' },
      { char: '般', name: '일반 반', pinyin: 'bān' },
      { char: '舰', name: '싸움배 함', pinyin: 'jiàn' },
    ],
  },
  {
    day: 53,
    level: 3,
    emoji: '🪶',
    radical: {
      char: '羽',
      name: '깃 우',
      cnName: '羽字旁',
      pinyin: 'yǔ',
      desc: '깃털',
    },
    related: [
      { char: '羽', name: '깃 우', pinyin: 'yǔ' },
      { char: '翅', name: '날개 시', pinyin: 'chì' },
      { char: '翔', name: '날 상', pinyin: 'xiáng' },
      { char: '翠', name: '푸를 취', pinyin: 'cuì' },
      { char: '翼', name: '날개 익', pinyin: 'yì' },
    ],
  },
  {
    day: 54,
    level: 3,
    emoji: '🕸️',
    radical: {
      char: '网',
      name: '그물 망',
      cnName: '网字头',
      pinyin: 'wǎng',
      desc: '그물',
    },
    related: [
      { char: '网', name: '그물 망', pinyin: 'wǎng' },
      { char: '罗', name: '벌일 라', pinyin: 'luó' },
      { char: '罚', name: '벌할 벌', pinyin: 'fá' },
      { char: '罪', name: '허물 죄', pinyin: 'zuì' },
      { char: '罩', name: '덮을 조', pinyin: 'zhào' },
    ],
  },
  {
    day: 55,
    level: 3,
    emoji: '🫘',
    radical: {
      char: '豆',
      name: '콩 두',
      cnName: '豆字旁',
      pinyin: 'dòu',
      desc: '콩',
    },
    related: [
      { char: '豆', name: '콩 두', pinyin: 'dòu' },
      { char: '短', name: '짧을 단', pinyin: 'duǎn' },
      { char: '登', name: '오를 등', pinyin: 'dēng' },
      { char: '鼓', name: '북 고', pinyin: 'gǔ' },
      { char: '豌', name: '완두 완', pinyin: 'wān' },
    ],
  },
  {
    day: 56,
    level: 3,
    emoji: '🍈',
    radical: {
      char: '瓜',
      name: '오이 과',
      cnName: '瓜字旁',
      pinyin: 'guā',
      desc: '참외·오이',
    },
    related: [
      { char: '瓜', name: '오이 과', pinyin: 'guā' },
      { char: '狐', name: '여우 호', pinyin: 'hú' },
      { char: '孤', name: '외로울 고', pinyin: 'gū' },
      { char: '瓢', name: '박 표', pinyin: 'piáo' },
      { char: '瓣', name: '꽃잎 판', pinyin: 'bàn' },
    ],
  },
  {
    day: 57,
    level: 3,
    emoji: '🌱',
    radical: {
      char: '麻',
      name: '삼 마',
      cnName: '麻字头',
      pinyin: 'má',
      desc: '삼',
    },
    related: [
      { char: '麻', name: '삼 마', pinyin: 'má' },
      { char: '磨', name: '갈 마', pinyin: 'mó' },
      { char: '魔', name: '마귀 마', pinyin: 'mó' },
      { char: '摩', name: '만질 마', pinyin: 'mó' },
      { char: '麾', name: '대장기 휘', pinyin: 'huī' },
    ],
  },
  {
    day: 58,
    level: 3,
    emoji: '🌾',
    radical: {
      char: '禾',
      name: '벼 화',
      cnName: '禾字旁',
      pinyin: 'hé',
      desc: '벼',
    },
    related: [
      { char: '禾', name: '벼 화', pinyin: 'hé' },
      { char: '和', name: '화할 화', pinyin: 'hé' },
      { char: '秋', name: '가을 추', pinyin: 'qiū' },
      { char: '种', name: '씨 종', pinyin: 'zhǒng' },
      { char: '科', name: '과정 과', pinyin: 'kē' },
    ],
  },
  {
    day: 59,
    level: 3,
    emoji: '🍚',
    radical: {
      char: '米',
      name: '쌀 미',
      cnName: '米字旁',
      pinyin: 'mǐ',
      desc: '쌀',
    },
    related: [
      { char: '米', name: '쌀 미', pinyin: 'mǐ' },
      { char: '粉', name: '가루 분', pinyin: 'fěn' },
      { char: '粮', name: '양식 량', pinyin: 'liáng' },
      { char: '粥', name: '죽 죽', pinyin: 'zhōu' },
      { char: '糖', name: '사탕 당', pinyin: 'táng' },
    ],
  },
  {
    day: 60,
    level: 3,
    emoji: '🏡',
    radical: {
      char: '广',
      name: '엄 호',
      cnName: '广字旁',
      pinyin: 'guǎng',
      desc: '집',
    },
    related: [
      { char: '广', name: '넓을 광', pinyin: 'guǎng' },
      { char: '店', name: '가게 점', pinyin: 'diàn' },
      { char: '床', name: '평상 상', pinyin: 'chuáng' },
      { char: '府', name: '마을 부', pinyin: 'fǔ' },
      { char: '座', name: '자리 좌', pinyin: 'zuò' },
    ],
  },

  // =====================================
  // 🚶 레벨 4: 행동 부수 (20개)
  // =====================================
  {
    day: 61,
    level: 4,
    emoji: '🚶',
    radical: {
      char: '行',
      name: '다닐 행',
      cnName: '行字旁',
      pinyin: 'xíng',
      desc: '가다',
    },
    related: [
      { char: '行', name: '다닐 행', pinyin: 'xíng' },
      { char: '街', name: '거리 가', pinyin: 'jiē' },
      { char: '衍', name: '넘칠 연', pinyin: 'yǎn' },
      { char: '衡', name: '저울 형', pinyin: 'héng' },
      { char: '衔', name: '재갈 함', pinyin: 'xián' },
    ],
  },
  {
    day: 62,
    level: 4,
    emoji: '🏃',
    radical: {
      char: '走',
      name: '달릴 주',
      cnName: '走字旁',
      pinyin: 'zǒu',
      desc: '달리다',
    },
    related: [
      { char: '走', name: '달릴 주', pinyin: 'zǒu' },
      { char: '起', name: '일어날 기', pinyin: 'qǐ' },
      { char: '越', name: '넘을 월', pinyin: 'yuè' },
      { char: '赶', name: '쫓을 간', pinyin: 'gǎn' },
      { char: '趣', name: '뜻 취', pinyin: 'qù' },
    ],
  },
  {
    day: 63,
    level: 4,
    emoji: '✋',
    radical: {
      char: '止',
      name: '그칠 지',
      cnName: '止字旁',
      pinyin: 'zhǐ',
      desc: '멈추다',
    },
    related: [
      { char: '止', name: '그칠 지', pinyin: 'zhǐ' },
      { char: '正', name: '바를 정', pinyin: 'zhèng' },
      { char: '此', name: '이 차', pinyin: 'cǐ' },
      { char: '步', name: '걸음 보', pinyin: 'bù' },
      { char: '武', name: '굳셀 무', pinyin: 'wǔ' },
    ],
  },
  {
    day: 64,
    level: 4,
    emoji: '🤚',
    radical: {
      char: '又',
      name: '또 우',
      cnName: '又字旁',
      pinyin: 'yòu',
      desc: '손',
    },
    related: [
      { char: '又', name: '또 우', pinyin: 'yòu' },
      { char: '双', name: '쌍 쌍', pinyin: 'shuāng' },
      { char: '友', name: '벗 우', pinyin: 'yǒu' },
      { char: '取', name: '취할 취', pinyin: 'qǔ' },
      { char: '受', name: '받을 수', pinyin: 'shòu' },
    ],
  },
  {
    day: 65,
    level: 4,
    emoji: '🐾',
    radical: {
      char: '爪',
      name: '손톱 조',
      cnName: '爪字头',
      pinyin: 'zhǎo',
      desc: '손톱',
    },
    related: [
      { char: '爪', name: '손톱 조', pinyin: 'zhǎo' },
      { char: '采', name: '캘 채', pinyin: 'cǎi' },
      { char: '受', name: '받을 수', pinyin: 'shòu' },
      { char: '爱', name: '사랑 애', pinyin: 'ài' },
      { char: '爵', name: '벼슬 작', pinyin: 'jué' },
    ],
  },
  {
    day: 66,
    level: 4,
    emoji: '👊',
    radical: {
      char: '攵',
      name: '등글월문',
      cnName: '反文旁',
      pinyin: 'pū',
      desc: '치다',
    },
    related: [
      { char: '放', name: '놓을 방', pinyin: 'fàng' },
      { char: '教', name: '가르칠 교', pinyin: 'jiào' },
      { char: '故', name: '연고 고', pinyin: 'gù' },
      { char: '改', name: '고칠 개', pinyin: 'gǎi' },
      { char: '收', name: '거둘 수', pinyin: 'shōu' },
    ],
  },
  {
    day: 67,
    level: 4,
    emoji: '⚔️',
    radical: {
      char: '殳',
      name: '몽둥이 수',
      cnName: '殳字旁',
      pinyin: 'shū',
      desc: '무기',
    },
    related: [
      { char: '殳', name: '몽둥이 수', pinyin: 'shū' },
      { char: '段', name: '조각 단', pinyin: 'duàn' },
      { char: '殿', name: '전각 전', pinyin: 'diàn' },
      { char: '毁', name: '헐 훼', pinyin: 'huǐ' },
      { char: '毅', name: '굳셀 의', pinyin: 'yì' },
    ],
  },
  {
    day: 68,
    level: 4,
    emoji: '🏹',
    radical: {
      char: '弓',
      name: '활 궁',
      cnName: '弓字旁',
      pinyin: 'gōng',
      desc: '활',
    },
    related: [
      { char: '弓', name: '활 궁', pinyin: 'gōng' },
      { char: '张', name: '베풀 장', pinyin: 'zhāng' },
      { char: '强', name: '강할 강', pinyin: 'qiáng' },
      { char: '弹', name: '탄알 탄', pinyin: 'tán' },
      { char: '引', name: '끌 인', pinyin: 'yǐn' },
    ],
  },
  {
    day: 69,
    level: 4,
    emoji: '🗡️',
    radical: {
      char: '戈',
      name: '창 과',
      cnName: '戈字旁',
      pinyin: 'gē',
      desc: '창',
    },
    related: [
      { char: '戈', name: '창 과', pinyin: 'gē' },
      { char: '战', name: '싸울 전', pinyin: 'zhàn' },
      { char: '成', name: '이룰 성', pinyin: 'chéng' },
      { char: '我', name: '나 아', pinyin: 'wǒ' },
      { char: '戏', name: '놀희 희', pinyin: 'xì' },
    ],
  },
  {
    day: 70,
    level: 4,
    emoji: '🖌️',
    radical: {
      char: '聿',
      name: '붓 율',
      cnName: '聿字旁',
      pinyin: 'yù',
      desc: '붓',
    },
    related: [
      { char: '聿', name: '붓 율', pinyin: 'yù' },
      { char: '律', name: '법칙 률', pinyin: 'lǜ' },
      { char: '建', name: '세울 건', pinyin: 'jiàn' },
      { char: '健', name: '굳셀 건', pinyin: 'jiàn' },
      { char: '肆', name: '방자할 사', pinyin: 'sì' },
    ],
  },
  {
    day: 71,
    level: 4,
    emoji: '🧍',
    radical: {
      char: '身',
      name: '몸 신',
      cnName: '身字旁',
      pinyin: 'shēn',
      desc: '몸',
    },
    related: [
      { char: '身', name: '몸 신', pinyin: 'shēn' },
      { char: '射', name: '쏠 사', pinyin: 'shè' },
      { char: '躲', name: '숨을 타', pinyin: 'duǒ' },
      { char: '躺', name: '누울 당', pinyin: 'tǎng' },
      { char: '躯', name: '몸 구', pinyin: 'qū' },
    ],
  },
  {
    day: 72,
    level: 4,
    emoji: '🪓',
    radical: {
      char: '斤',
      name: '도끼 근',
      cnName: '斤字旁',
      pinyin: 'jīn',
      desc: '도끼',
    },
    related: [
      { char: '斤', name: '도끼 근', pinyin: 'jīn' },
      { char: '斩', name: '벨 참', pinyin: 'zhǎn' },
      { char: '断', name: '끊을 단', pinyin: 'duàn' },
      { char: '新', name: '새 신', pinyin: 'xīn' },
      { char: '斯', name: '이 사', pinyin: 'sī' },
    ],
  },
  {
    day: 73,
    level: 4,
    emoji: '🥱',
    radical: {
      char: '欠',
      name: '하품 흠',
      cnName: '欠字旁',
      pinyin: 'qiàn',
      desc: '하품하다',
    },
    related: [
      { char: '欠', name: '하품 흠', pinyin: 'qiàn' },
      { char: '次', name: '버금 차', pinyin: 'cì' },
      { char: '欢', name: '기쁠 환', pinyin: 'huān' },
      { char: '欧', name: '토할 구', pinyin: 'ōu' },
      { char: '歌', name: '노래 가', pinyin: 'gē' },
    ],
  },
  {
    day: 74,
    level: 4,
    emoji: '🚶‍♂️',
    radical: {
      char: '夂',
      name: '뒤져올치',
      cnName: '折文旁',
      pinyin: 'zhǐ',
      desc: '천천히 걷다',
    },
    related: [
      { char: '夂', name: '뒤져올 치', pinyin: 'zhǐ' },
      { char: '各', name: '각각 각', pinyin: 'gè' },
      { char: '冬', name: '겨울 동', pinyin: 'dōng' },
      { char: '备', name: '갖출 비', pinyin: 'bèi' },
      { char: '复', name: '회복할 복', pinyin: 'fù' },
    ],
  },
  {
    day: 75,
    level: 4,
    emoji: '📏',
    radical: {
      char: '寸',
      name: '마디 촌',
      cnName: '寸字旁',
      pinyin: 'cùn',
      desc: '재다',
    },
    related: [
      { char: '寸', name: '마디 촌', pinyin: 'cùn' },
      { char: '对', name: '대할 대', pinyin: 'duì' },
      { char: '寺', name: '절 사', pinyin: 'sì' },
      { char: '封', name: '봉할 봉', pinyin: 'fēng' },
      { char: '导', name: '이끌 도', pinyin: 'dǎo' },
    ],
  },
  {
    day: 76,
    level: 4,
    emoji: '🌿',
    radical: {
      char: '支',
      name: '지탱할 지',
      cnName: '支字旁',
      pinyin: 'zhī',
      desc: '가지치다',
    },
    related: [
      { char: '支', name: '지탱할 지', pinyin: 'zhī' },
      { char: '枝', name: '가지 지', pinyin: 'zhī' },
      { char: '技', name: '재주 기', pinyin: 'jì' },
      { char: '歧', name: '갈림길 기', pinyin: 'qí' },
      { char: '鼓', name: '북 고', pinyin: 'gǔ' },
    ],
  },
  {
    day: 77,
    level: 4,
    emoji: '🕊️',
    radical: {
      char: '飞',
      name: '날 비',
      cnName: '飞字旁',
      pinyin: 'fēi',
      desc: '날다',
    },
    related: [
      { char: '飞', name: '날 비', pinyin: 'fēi' },
      { char: '机', name: '틀 기', pinyin: 'jī' },
      { char: '风', name: '바람 풍', pinyin: 'fēng' },
      { char: '飘', name: '회오리 표', pinyin: 'piāo' },
      { char: '飙', name: '폭풍 표', pinyin: 'biāo' },
    ],
  },
  {
    day: 78,
    level: 4,
    emoji: '🛠️',
    radical: {
      char: '用',
      name: '쓸 용',
      cnName: '用字旁',
      pinyin: 'yòng',
      desc: '쓰다',
    },
    related: [
      { char: '用', name: '쓸 용', pinyin: 'yòng' },
      { char: '甩', name: '버릴 무', pinyin: 'shuǎi' },
      { char: '甫', name: '클 보', pinyin: 'fǔ' },
      { char: '甬', name: '길 용', pinyin: 'yǒng' },
      { char: '痛', name: '아플 통', pinyin: 'tòng' },
    ],
  },
  {
    day: 79,
    level: 4,
    emoji: '💪',
    radical: {
      char: '力',
      name: '힘 력',
      cnName: '力字旁',
      pinyin: 'lì',
      desc: '힘쓰다',
    },
    related: [
      { char: '力', name: '힘 력', pinyin: 'lì' },
      { char: '办', name: '힘쓸 판', pinyin: 'bàn' },
      { char: '加', name: '더할 가', pinyin: 'jiā' },
      { char: '动', name: '움직일 동', pinyin: 'dòng' },
      { char: '男', name: '사내 남', pinyin: 'nán' },
    ],
  },
  {
    day: 80,
    level: 4,
    emoji: '🤲',
    radical: {
      char: '及',
      name: '미칠 급',
      cnName: '及字旁',
      pinyin: 'jí',
      desc: '미치다',
    },
    related: [
      { char: '及', name: '미칠 급', pinyin: 'jí' },
      { char: '级', name: '등급 급', pinyin: 'jí' },
      { char: '吸', name: '마실 흡', pinyin: 'xī' },
      { char: '极', name: '다할 극', pinyin: 'jí' },
      { char: '汲', name: '길을 급', pinyin: 'jí' },
    ],
  },

  // =====================================
  // 💭 레벨 5: 상태·감각·신체 부수 (20개)
  // =====================================
  {
    day: 81,
    level: 5,
    emoji: '🎵',
    radical: {
      char: '音',
      name: '소리 음',
      cnName: '音字旁',
      pinyin: 'yīn',
      desc: '소리',
    },
    related: [
      { char: '音', name: '소리 음', pinyin: 'yīn' },
      { char: '意', name: '뜻 의', pinyin: 'yì' },
      { char: '暗', name: '어두울 암', pinyin: 'àn' },
      { char: '韵', name: '운치 운', pinyin: 'yùn' },
      { char: '章', name: '글 장', pinyin: 'zhāng' },
    ],
  },
  {
    day: 82,
    level: 5,
    emoji: '🌈',
    radical: {
      char: '色',
      name: '빛 색',
      cnName: '色字旁',
      pinyin: 'sè',
      desc: '색',
    },
    related: [
      { char: '色', name: '빛 색', pinyin: 'sè' },
      { char: '艳', name: '고울 염', pinyin: 'yàn' },
      { char: '绝', name: '끊을 절', pinyin: 'jué' },
      { char: '艴', name: '성낼 불', pinyin: 'fú' },
      { char: '艵', name: '합할 병', pinyin: 'pǐng' },
    ],
  },
  {
    day: 83,
    level: 5,
    emoji: '🌸',
    radical: {
      char: '香',
      name: '향기 향',
      cnName: '香字旁',
      pinyin: 'xiāng',
      desc: '향기',
    },
    related: [
      { char: '香', name: '향기 향', pinyin: 'xiāng' },
      { char: '馨', name: '향기 형', pinyin: 'xīn' },
      { char: '馥', name: '향기 복', pinyin: 'fù' },
      { char: '馡', name: '향기 비', pinyin: 'fēi' },
      { char: '馫', name: '향기 흥', pinyin: 'xīn' },
    ],
  },
  {
    day: 84,
    level: 5,
    emoji: '🌱',
    radical: {
      char: '生',
      name: '날 생',
      cnName: '生字旁',
      pinyin: 'shēng',
      desc: '삶',
    },
    related: [
      { char: '生', name: '날 생', pinyin: 'shēng' },
      { char: '性', name: '성품 성', pinyin: 'xìng' },
      { char: '星', name: '별 성', pinyin: 'xīng' },
      { char: '姓', name: '성 성', pinyin: 'xìng' },
      { char: '牲', name: '희생 생', pinyin: 'shēng' },
    ],
  },
  {
    day: 85,
    level: 5,
    emoji: '👴',
    radical: {
      char: '老',
      name: '늙을 로',
      cnName: '老字头',
      pinyin: 'lǎo',
      desc: '늙다',
    },
    related: [
      { char: '老', name: '늙을 로', pinyin: 'lǎo' },
      { char: '考', name: '생각할 고', pinyin: 'kǎo' },
      { char: '者', name: '놈 자', pinyin: 'zhě' },
      { char: '孝', name: '효도 효', pinyin: 'xiào' },
      { char: '耆', name: '늙은이 기', pinyin: 'qí' },
    ],
  },
  {
    day: 86,
    level: 5,
    emoji: '🧍',
    radical: {
      char: '立',
      name: '설 립',
      cnName: '立字旁',
      pinyin: 'lì',
      desc: '서다',
    },
    related: [
      { char: '立', name: '설 립', pinyin: 'lì' },
      { char: '站', name: '우두커니 참', pinyin: 'zhàn' },
      { char: '童', name: '아이 동', pinyin: 'tóng' },
      { char: '端', name: '바를 단', pinyin: 'duān' },
      { char: '章', name: '글 장', pinyin: 'zhāng' },
    ],
  },
  {
    day: 87,
    level: 5,
    emoji: '🙋',
    radical: {
      char: '自',
      name: '스스로 자',
      cnName: '自字旁',
      pinyin: 'zì',
      desc: '스스로',
    },
    related: [
      { char: '自', name: '스스로 자', pinyin: 'zì' },
      { char: '息', name: '쉴 식', pinyin: 'xī' },
      { char: '臭', name: '냄새 취', pinyin: 'chòu' },
      { char: '鼻', name: '코 비', pinyin: 'bí' },
      { char: '臬', name: '법 녈', pinyin: 'niè' },
    ],
  },
  {
    day: 88,
    level: 5,
    emoji: '❌',
    radical: {
      char: '非',
      name: '아닐 비',
      cnName: '非字旁',
      pinyin: 'fēi',
      desc: '아니다',
    },
    related: [
      { char: '非', name: '아닐 비', pinyin: 'fēi' },
      { char: '靠', name: '기댈 고', pinyin: 'kào' },
      { char: '悲', name: '슬플 비', pinyin: 'bēi' },
      { char: '辈', name: '세대 배', pinyin: 'bèi' },
      { char: '斐', name: '문채 비', pinyin: 'fěi' },
    ],
  },
  {
    day: 89,
    level: 5,
    emoji: '⚪',
    radical: {
      char: '白',
      name: '흰 백',
      cnName: '白字旁',
      pinyin: 'bái',
      desc: '희다',
    },
    related: [
      { char: '白', name: '흰 백', pinyin: 'bái' },
      { char: '的', name: '과녁 적', pinyin: 'de' },
      { char: '百', name: '일백 백', pinyin: 'bǎi' },
      { char: '皇', name: '임금 황', pinyin: 'huáng' },
      { char: '皆', name: '다 개', pinyin: 'jiē' },
    ],
  },
  {
    day: 90,
    level: 5,
    emoji: '⚫',
    radical: {
      char: '黑',
      name: '검을 흑',
      cnName: '黑字旁',
      pinyin: 'hēi',
      desc: '검다',
    },
    related: [
      { char: '黑', name: '검을 흑', pinyin: 'hēi' },
      { char: '默', name: '잠잠할 묵', pinyin: 'mò' },
      { char: '墨', name: '먹 묵', pinyin: 'mò' },
      { char: '黛', name: '눈썹먹 대', pinyin: 'dài' },
      { char: '黯', name: '검을 암', pinyin: 'àn' },
    ],
  },
  {
    day: 91,
    level: 5,
    emoji: '🔵',
    radical: {
      char: '青',
      name: '푸를 청',
      cnName: '青字旁',
      pinyin: 'qīng',
      desc: '푸르다',
    },
    related: [
      { char: '青', name: '푸를 청', pinyin: 'qīng' },
      { char: '清', name: '맑을 청', pinyin: 'qīng' },
      { char: '情', name: '뜻 정', pinyin: 'qíng' },
      { char: '晴', name: '괼 청', pinyin: 'qíng' },
      { char: '请', name: '청할 청', pinyin: 'qǐng' },
    ],
  },
  {
    day: 92,
    level: 5,
    emoji: '🔴',
    radical: {
      char: '赤',
      name: '붉을 적',
      cnName: '赤字旁',
      pinyin: 'chì',
      desc: '붉다',
    },
    related: [
      { char: '赤', name: '붉을 적', pinyin: 'chì' },
      { char: '赦', name: '용서할 사', pinyin: 'shè' },
      { char: '赫', name: '빛날 혁', pinyin: 'hè' },
      { char: '赭', name: '붉은흙 자', pinyin: 'zhě' },
      { char: '赧', name: '붉힐 난', pinyin: 'nǎn' },
    ],
  },
  {
    day: 93,
    level: 5,
    emoji: '✨',
    radical: {
      char: '示',
      name: '보일 시',
      cnName: '示字旁',
      pinyin: 'shì',
      desc: '보이다',
    },
    related: [
      { char: '示', name: '보일 시', pinyin: 'shì' },
      { char: '票', name: '표 표', pinyin: 'piào' },
      { char: '禁', name: '금할 금', pinyin: 'jìn' },
      { char: '祭', name: '제사 제', pinyin: 'jì' },
      { char: '祟', name: '빌미 수', pinyin: 'suì' },
    ],
  },
  {
    day: 94,
    level: 5,
    emoji: '🧠',
    radical: {
      char: '页',
      name: '머리 혈',
      cnName: '页字旁',
      pinyin: 'yè',
      desc: '머리',
    },
    related: [
      { char: '页', name: '머리 혈', pinyin: 'yè' },
      { char: '顶', name: '정수리 정', pinyin: 'dǐng' },
      { char: '项', name: '항목 항', pinyin: 'xiàng' },
      { char: '顺', name: '순할 순', pinyin: 'shùn' },
      { char: '题', name: '제목 제', pinyin: 'tí' },
    ],
  },
  {
    day: 95,
    level: 5,
    emoji: '👑',
    radical: {
      char: '首',
      name: '머리 수',
      cnName: '首字旁',
      pinyin: 'shǒu',
      desc: '머리',
    },
    related: [
      { char: '首', name: '머리 수', pinyin: 'shǒu' },
      { char: '道', name: '길 도', pinyin: 'dào' },
      { char: '馗', name: '아홉갈래길 규', pinyin: 'kuí' },
      { char: '馘', name: '괵 괵', pinyin: 'guó' },
      { char: '馦', name: '향기 향', pinyin: 'xiān' },
    ],
  },
  {
    day: 96,
    level: 5,
    emoji: '🙂',
    radical: {
      char: '面',
      name: '낯 면',
      cnName: '面字旁',
      pinyin: 'miàn',
      desc: '얼굴',
    },
    related: [
      { char: '面', name: '낯 면', pinyin: 'miàn' },
      { char: '脸', name: '뺨 렴', pinyin: 'liǎn' },
      { char: '靣', name: '낯 면', pinyin: 'miàn' },
      { char: '麺', name: '국수 면', pinyin: 'miàn' },
      { char: '腼', name: '부끄러워할 면', pinyin: 'miǎn' },
    ],
  },
  {
    day: 97,
    level: 5,
    emoji: '👃',
    radical: {
      char: '鼻',
      name: '코 비',
      cnName: '鼻字旁',
      pinyin: 'bí',
      desc: '코',
    },
    related: [
      { char: '鼻', name: '코 비', pinyin: 'bí' },
      { char: '鼾', name: '코골 한', pinyin: 'hān' },
      { char: '鼽', name: '코막힐 구', pinyin: 'qiú' },
      { char: '鼢', name: '두더지 분', pinyin: 'fén' },
      { char: '鼩', name: '땃쥐 구', pinyin: 'qú' },
    ],
  },
  {
    day: 98,
    level: 5,
    emoji: '👅',
    radical: {
      char: '舌',
      name: '혀 설',
      cnName: '舌字旁',
      pinyin: 'shé',
      desc: '혀',
    },
    related: [
      { char: '舌', name: '혀 설', pinyin: 'shé' },
      { char: '甜', name: '달 첨', pinyin: 'tián' },
      { char: '乱', name: '어지러울 란', pinyin: 'luàn' },
      { char: '辞', name: '말씀 사', pinyin: 'cí' },
      { char: '舔', name: '핥을 첨', pinyin: 'tiǎn' },
    ],
  },
  {
    day: 99,
    level: 5,
    emoji: '🦴',
    radical: {
      char: '骨',
      name: '뼈 골',
      cnName: '骨字旁',
      pinyin: 'gǔ',
      desc: '뼈',
    },
    related: [
      { char: '骨', name: '뼈 골', pinyin: 'gǔ' },
      { char: '骂', name: '꾸짖을 매', pinyin: 'mà' },
      { char: '骄', name: '교만할 교', pinyin: 'jiāo' },
      { char: '骰', name: '주사위 투', pinyin: 'tóu' },
      { char: '髓', name: '골수 수', pinyin: 'suǐ' },
    ],
  },
  {
    day: 100,
    level: 5,
    emoji: '🩸',
    radical: {
      char: '血',
      name: '피 혈',
      cnName: '血字旁',
      pinyin: 'xuè',
      desc: '피',
    },
    related: [
      { char: '血', name: '피 혈', pinyin: 'xuè' },
      { char: '衅', name: '피바를 흔', pinyin: 'xìn' },
      { char: '衄', name: '코피 뉵', pinyin: 'nǜ' },
      { char: '衃', name: '엉긴피 배', pinyin: 'pēi' },
      { char: '衂', name: '코피 뉵', pinyin: 'nǜ' },
    ],
  },
];
